# Generated by Django 3.1.4 on 2020-12-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0002_auto_20201228_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
