# Generated by Django 3.1.4 on 2020-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_auto_20201228_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
