# Generated by Django 3.1.4 on 2020-12-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201228_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='plant',
        ),
    ]
