# Generated by Django 3.1.4 on 2020-12-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201228_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='plant',
        ),
    ]
